import{S as a}from"./assets/vendor-874053e3.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function e(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(t){if(t.ep)return;t.ep=!0;const r=e(t);fetch(t.href,r)}})();const l=document.querySelector(".gallery"),c=document.querySelector(".form");function u(o){c.reset();const s=o.map(e=>`<div class="card"><a class="gallery-link" href="${e.largeImageURL}">
          <img class="gallery-image" src="${e.webformatURL}" alt="${e.tags}" />
        </a>
        <ul class="list">
          <li class="item">Likes: <span>${e.likes}</span></li>
          <li class="item">Views: <span>${e.views}</span></li>
          <li class="item">Comments: <span>${e.comments}</span></li>
          <li class="item">Downloads: <span>${e.downloads}</span></li>
        </ul></div>`).join("");l.innerHTML=s}document.querySelector("button");const m=document.querySelector(".search");function f(){let o=m.value;const s=`https://pixabay.com/api/?key=42766573-a347fa67a5b7233d1286bfaa7&q=${o}&image_type=photo&orientation=horizontal&safesearch=true`;o&&fetch(s).then(e=>{if(!e.ok)throw new Error(e.status);return e.json()}).then(e=>{e.hits.length===0?iziToast.error({title:"",message:"Sorry, there are no images matching your search query. Please try again!"}):(e.totalHits,e.total,e.hits,u(e.hits))}).catch(e=>{console.log(e),iziToast.error({title:"",message:"Sorry, there are no images matching your search query. Please try again!"})})}document.querySelector("button");document.querySelector(".search");document.querySelector(".gallery");const y=document.querySelector(".form");y.addEventListener("submit",function(o){o.preventDefault(),f()});const d=new a(".gallery a",{captionDelay:250,captionsData:"alt"});d.refresh();
//# sourceMappingURL=commonHelpers.js.map
